services:
  app:
    container_name: deepface_custom
    build: 
      context: ./deepface_customization
    env_file:
      - ./deepface_customization/.env
    ports:
      - "5050:8000"
    restart: unless-stopped
    networks: 
      - deepface_custom
    volumes:
      - .:/FaceRecognition
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
networks:
  deepface_custom:
    driver: bridge

